Repository boostcampwm-2021/WEB27-NogariHouse, pull requests merged in 2021-12, with the labels that each got.

#155 ♻️ Client 부분 Socket message 상수화
  client/src/components/chat/detail-view/index.tsx
  client/src/components/chat/new-view/header/chat-new-header.tsx
  client/src/components/common/default-header/index.tsx
  client/src/components/main/left-sidebar/index.tsx
  client/src/components/profile/modal/change-profile-image/index.tsx
  client/src/components/room/in-view/index.tsx
  client/src/components/room/modal/follower-select-header.tsx
  client/src/constants/socket-message/chat.ts
  client/src/constants/socket-message/room.ts
  client/src/constants/socket-message/user.ts
  client/src/constants/toast-mssage.ts
  client/src/hooks/useRtc.tsx
  client/tsconfig.path.json
Labels: ♻️ refactor

#157 채팅방 관련 버그 수정
  client/src/components/chat/detail-view/footer/index.tsx
  client/src/components/common/default-header/index.tsx
  server/src/sockets/chat.ts
Labels: 🐠 front-end, 🐟 back-end, 🐛 bug

#159 ✨ 방 접속 인원 제한 & in-view 테스트 코드 작성
  client/src/components/common/room-card/index.tsx
  client/src/components/room/in-view/index.tsx
  client/src/components/room/new-view/index.test.tsx
Labels: ✨ feature

#164 ♻️ Any 사용된 부분 없애주기
  client/src/components/chat/detail-view/footer/index.tsx
  client/src/components/chat/detail-view/header/index.tsx
  client/src/components/chat/detail-view/index.tsx
  client/src/components/chat/detail-view/reducer.ts
  server/src/models/chats.ts
  server/src/services/chat-service.ts
  server/src/sockets/chat.ts
  server/src/sockets/room.ts
Labels: ♻️ refactor

#165 ♻️ Refactor : QA 해결하기 & FE 성능 개선하기
  client/src/api/user/index.ts
  client/src/assets/styles/global-styles.ts
  client/src/assets/styles/select.tsx
  client/src/components/common/default-header/index.tsx
  client/src/components/common/menu-modal/index.tsx
  client/src/components/event/register-modal/style.ts
  client/src/components/main/left-sidebar/active-following-card/style.ts
  client/src/components/profile/modal/change-profile-image/index.tsx
  client/src/components/room/in-view/style.ts
  client/src/components/sign/signup-info-view/index.tsx
  client/src/hooks/useIsFollowingRef.tsx
  client/src/utils/index.tsx
  server/src/api/middlewares/image-upload.ts
Labels: 🐠 front-end, ♻️ refactor

#168 🐛 메세지 입력후 스크롤이 정상적으로 내려가지 않는 버그 수정
  client/src/components/chat/detail-view/index.tsx
Labels: 🐛 bug

#169 마이크 off 일 때 접속 이슈
  client/src/components/room/modal/follower-select-header.tsx
  client/src/components/room/new-view/index.tsx
  client/src/constants/toast-message.ts
  client/src/hooks/useRtc.tsx
  server/src/sockets/room.ts
Labels: 🐛 bug

#171 ⚡️ left / right sidebar 렌더링 최적화
  client/src/components/common/default-button/index.tsx
  client/src/components/main/left-sidebar/index.tsx
  client/src/components/main/right-sidebar/index.tsx
  client/src/components/room/new-view/index.tsx
Labels: ♻️ refactor
