Repository boostcampwm-2021/WEB27-NogariHouse, pull requests merged in 2021-11, with the labels that each got.

#1 🎉 프로젝트 초기설정
  .vscode/settings.json
  client/.eslintrc.json
  client/.gitignore
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.tsx
  client/src/api/index.ts
  client/src/components/index.tsx
  client/src/components/styled-components/index.tsx
  client/src/hooks/index.tsx
  client/src/index.tsx
  client/src/react-app-env.d.ts
  client/src/recoli/atoms/index.ts
  client/src/recoli/selectors/index.ts
  client/src/routes/index.tsx
  client/src/routes/main.tsx
  client/src/tests/index.tsx
  client/src/types/index.tsx
  client/src/utils/index.tsx
  client/src/views/activity-view.tsx
  client/src/views/chat-room-detail-view.tsx
  client/src/views/chat-rooms-new-view.tsx
  client/src/views/chat-rooms-view.tsx
  client/src/views/event-view.tsx
  client/src/views/followers-view.tsx
  client/src/views/following-view.tsx
  client/src/views/invite-view.tsx
  client/src/views/main-view.tsx
  client/src/views/profile-settings-view.tsx
  client/src/views/profile-view.tsx
  client/src/views/recent-search-view.tsx
  client/src/views/serach-view.tsx
  client/src/views/signin-view.tsx
  client/src/views/signup-view.tsx
  client/tsconfig.json
  client/yarn.lock
  server/.env
  server/.eslintrc.json
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/api/index.ts
  server/src/api/middlewares/error-handler.ts
  server/src/api/routes/main.ts
  server/src/app.ts
  server/src/config/index.ts
  server/src/loaders/express.ts
  server/src/loaders/index.ts
  server/src/utils/http-exception.ts
  server/tsconfig.json
  server/yarn.lock
Labels: 🗂️ chore

#2 import alias 설정
  client/craco.config.js
  client/package.json
  client/src/routes/main.tsx
  client/src/views/search-view.tsx
  client/tsconfig.json
  client/tsconfig.path.json
  client/yarn.lock
  server/.eslintrc.json
  server/package.json
  server/src/api/middlewares/error-handler.ts
  server/src/app.ts
  server/tsconfig.json
  server/yarn.lock
Labels: 🗂️ chore

#12 초기 화면 UI 구현
  client/.eslintrc.json
  client/package.json
  client/src/App.tsx
  client/src/assets/fonts/Bangers/Bangers-Regular.ttf
  client/src/assets/fonts/fonts.ts
  client/src/assets/images/logo.svg
  client/src/assets/styles/global-styles.ts
  client/src/assets/styles/styled.d.ts
  client/src/components/large-logo.tsx
  client/src/components/styled-components/default-button.tsx
  client/src/components/styled-components/index.tsx
  client/src/index.tsx
  client/src/types/fonts.d.ts
  client/src/types/index.tsx
  client/src/views/main-view.tsx
  client/src/views/search-view.tsx
  client/tsconfig.path.json
  client/yarn.lock
  server/src/api/routes/main.ts
Labels: 🐠 front-end, 🗂️ chore, ❓ question, ♻️ refactor

#13 🔧 eslint 개행관련 설정 추가
  client/.eslintrc.json
Labels: 🗂️ chore

#16 create a room 모달 생성
  client/package.json
  client/src/components/right-sidebar.tsx
  client/src/components/room-type-check-box.tsx
  client/src/components/styled-components/default-button.tsx
  client/src/index.tsx
  client/src/recoil/atoms/room-type.ts
  client/src/recoil/selectors/index.ts
  client/src/recoli/selectors/index.ts
  client/yarn.lock
Labels: 🐠 front-end, ✨ feature

#18 ✨ room card 구현
  client/src/components/styled-components/room-card.tsx
  client/tsconfig.json
Labels: 🐠 front-end, ✨ feature

#17 활동중인 팔로잉 리스트 사이드바 구현
  client/src/assets/fonts/Nunito/Nunito-Regular.ttf
  client/src/assets/styles/global-styles.ts
  client/src/components/left-sidebar.tsx
  client/src/components/styled-components/active-following-card.tsx
Labels: 🐠 front-end, ✨ feature

#21 메인 room modal 생성
  client/src/components/anonymous-checkbox.tsx
  client/src/components/right-sidebar.tsx
  client/src/components/styled-components/small-checkbox.tsx
  server/src/api/index.ts
  server/src/api/routes/room.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#28 ✨이벤트 등록 모달 구현 (#9)
  client/src/components/event-register-modal.tsx
  client/src/components/styled-components/event-card.tsx
  client/src/views/event-view.tsx
  client/src/views/main-view.tsx
  server/src/api/routes/event.ts
  server/src/models/events.ts
  server/src/services/events-service.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#29 방 생성하기 DB 연동 (#6)
  client/src/components/right-sidebar.tsx
  server/package.json
  server/src/api/routes/room.ts
  server/src/models/rooms.ts
  server/src/services/rooms-service.ts
  server/yarn.lock
Labels: 🐟 back-end, 🐛 bug, ♻️ refactor

#36 방 생성 버튼 클릭 이후 로직 구현
  client/package.json
  client/src/components/in-room-modal.tsx
  client/src/components/right-sidebar.tsx
  client/src/components/room-modal.tsx
  client/src/recoil/atoms/socket.ts
  client/src/recoil/atoms/user.ts
  client/src/utils/index.tsx
  client/src/views/main-view.tsx
  client/yarn.lock
  server/package.json
  server/src/api/index.ts
  server/src/api/routes/main.ts
  server/src/api/routes/room.ts
  server/src/models/rooms.ts
  server/src/services/rooms-service.ts
  server/src/sockets/index.ts
  server/src/sockets/room.ts
  server/tsconfig.json
  server/yarn.lock
Labels: 🐠 front-end, 🐟 back-end, ♻️ refactor

#38 로그인 회원가입 구현
  client/src/assets/styles/keyframe.ts
  client/src/components/styled-components/loading-spinner.tsx
  client/src/utils/index.tsx
  client/src/views/main-view.tsx
  client/src/views/signup-info-view.tsx
  client/src/views/signup-view.tsx
  server/package.json
  server/src/api/routes/user.ts
  server/src/services/users-service.ts
  server/yarn.lock
Labels: 🐠 front-end, 🐟 back-end, ✨ feature, ❓ question

#42 [1-1][1-4] 로그인 & 회원가입 구현 완료
  client/package.json
  client/src/assets/styles/keyframe.ts
  client/src/components/event-header.tsx
  client/src/components/sign-header.tsx
  client/src/components/styled-components/custom-inputbar.tsx
  client/src/components/styled-components/interest-item.tsx
  client/src/components/styled-components/loading-spinner.tsx
  client/src/components/styled-components/sign-body.tsx
  client/src/components/styled-components/sign-title.tsx
  client/src/routes/index.tsx
  client/src/utils/index.tsx
  client/src/views/main-view.tsx
  client/src/views/signin-view.tsx
  client/src/views/signup-info-view.tsx
  client/src/views/signup-view.tsx
  client/yarn.lock
  server/package.json
  server/src/api/middlewares/auth.ts
  server/src/api/routes/user.ts
  server/src/loaders/express.ts
  server/src/models/refresh-token.ts
  server/src/models/users.ts
  server/src/services/users-service.ts
  server/src/utils/jwt-util.ts
  server/yarn.lock
Labels: 🐠 front-end, 🐟 back-end, ✨ feature, ♻️ refactor

#58 RoomCard 클릭시 Room 에 접속되는 기능 구현
  client/src/components/common/room-card.tsx
  client/src/views/room-view.tsx
Labels: 🐠 front-end, ✨ feature

#64 여러가지 버그 수정 및 유저 Room 접속 관련 추가 구현
  client/src/components/room/in-room-modal.tsx
  client/src/components/room/in-room-reducer.tsx
  client/src/recoil/atoms/room-document-id.ts
  server/src/services/rooms-service.ts
Labels: 🐠 front-end, 🐛 bug, ✨ feature, ❓ question, ♻️ refactor

#66 유저 접속 & 퇴장 기능 추가 및 음성 채팅 기능 추가(에러 발생)
  client/src/components/room/in-room-modal.tsx
  client/src/components/room/in-room-reducer.tsx
  client/src/components/room/in-room-user-box.tsx
  server/src/sockets/room.ts
Labels: 🐠 front-end, 🐟 back-end, 🐛 bug, ✨ feature, ❓ question

#67 이벤트 검색기능 구현
  client/public/favicon.ico
  client/public/index.html
  client/public/logo.svg
  client/src/assets/styles/scrollbar-style.ts
  client/src/components/common/default-header.tsx
  client/src/components/common/event-card.tsx
  client/src/components/common/room-card.tsx
  client/src/components/room/style.ts
  client/src/hooks/useFetchItems.tsx
  client/src/hooks/useSetEventModal.tsx
  client/src/views/event-view.tsx
  client/src/views/search-view.tsx
  server/src/api/routes/event.ts
  server/src/api/routes/search.ts
  server/src/services/events-service.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature, ♻️ refactor

#68 ♻️ search view에서 RoomCardLis 사용을 위한 코드 리팩토링
  client/src/views/room-view.tsx
Labels: ♻️ refactor

#71 검색 기능 추가 구현(Rooms)
  client/src/components/room/in-room-modal.tsx
  client/src/components/room/in-room-reducer.tsx
  client/src/views/search-view.tsx
  server/src/api/routes/search.ts
  server/src/services/events-service.ts
  server/src/services/rooms-service.ts
  server/src/services/users-service.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#73 Room 내부 마이크 토글 이벤트 구현
  client/src/components/room/in-room-modal.tsx
  client/src/components/room/in-room-reducer.tsx
  server/src/services/rooms-service.ts
  server/src/sockets/room.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#74 in-room-modal 관련 컴포넌트 리팩토링
  client/src/components/room/in-room-modal.tsx
  client/src/components/room/in-room-reducer.tsx
  client/src/components/room/in-room-user-box.tsx
  client/src/components/room/style.ts
  client/src/hooks/useSocket.tsx
  client/src/views/room-view.tsx
Labels: ♻️ refactor

#76 ✨User 검색 기능 구현
  client/src/components/common/default-button.tsx
  client/src/components/common/user-card-list.tsx
  client/src/components/common/user-card.tsx
  client/src/components/common/user-image.tsx
  client/src/recoil/atoms/user.ts
  client/src/views/following-view.tsx
  client/src/views/main-view.tsx
  client/src/views/search-view.tsx
  server/src/api/routes/search.ts
  server/src/api/routes/user.ts
  server/src/models/users.ts
  server/src/services/users-service.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature, ♻️ refactor

#77 🐡 [5-2] 채팅 목록 확인하기 구현
  client/src/api/index.ts
  client/src/components/chat/chat-header.tsx
  client/src/components/chat/chat-user-card.tsx
  client/src/components/common/default-header.tsx
  client/src/views/chat-rooms-view.tsx
  server/src/api/index.ts
  server/src/api/routes/chats.ts
  server/src/services/chat-service.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#80 RoomCard 관련 에러처리 / 스타일 수정
  client/src/api/index.ts
  client/src/components/common/room-card.tsx
  client/src/utils/index.tsx
  server/src/api/routes/room.ts
  server/src/services/rooms-service.ts
Labels: 🐛 bug, ✨ feature, ♻️ refactor

#81 followingList 전역상태관리 및 all 검색 기능을 위한 리팩토링
  client/src/api/index.ts
  client/src/components/common/user-card-list.tsx
  client/src/components/common/user-card.tsx
  client/src/components/search/option-bar.tsx
  client/src/components/search/search-type-check-box.tsx
  client/src/recoil/atoms/following-list.ts
  client/src/recoil/atoms/search-type.ts
  client/src/recoil/atoms/user.ts
  client/src/views/event-view.tsx
  client/src/views/following-view.tsx
  client/src/views/main-view.tsx
  client/src/views/room-view.tsx
  client/src/views/search-view.tsx
  server/src/api/routes/search.ts
  server/src/api/routes/user.ts
  server/src/models/users.ts
  server/src/services/events-service.ts
  server/src/services/rooms-service.ts
  server/src/services/users-service.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature, ♻️ refactor

#82 회원가입 유효성 검사 구현
  client/src/api/index.ts
  client/src/components/sign/sign-body.tsx
  client/src/components/sign/sign-title.tsx
  client/src/views/signup-info-view.tsx
  client/src/views/signup-view.tsx
  server/src/api/routes/user.ts
  server/src/services/users-service.ts
Labels: ✨ feature, ♻️ refactor

#83 음성채팅 기능 구현 🎉
  client/src/components/room/in-room-modal.tsx
  client/src/components/room/in-room-reducer.tsx
  client/src/components/room/in-room-user-box.tsx
  client/src/hooks/index.tsx
  client/src/hooks/useRtc.tsx
  client/src/hooks/useSocket.tsx
  client/src/recoil/atoms/user.ts
  client/src/utils/index.tsx
  server/package.json
  server/src/services/rooms-service.ts
  server/src/services/users-service.ts
  server/src/sockets/index.ts
  server/src/sockets/room.ts
Labels: 🐠 front-end, 🐟 back-end, 🐛 bug, ✨ feature, ♻️ refactor

#86 음성채팅 음소거 On&Off 반영 기능 추가
  client/src/components/common/default-button.tsx
  client/src/components/common/small-checkbox.tsx
  client/src/components/room/anonymous-checkbox.tsx
  client/src/components/room/in-room-modal.tsx
  client/src/components/room/in-room-user-box.tsx
  client/src/components/room/right-sidebar.tsx
  client/src/components/room/room-modal.tsx
  client/src/hooks/useRtc.tsx
  client/src/utils/test.js
  server/src/sockets/room.ts
Labels: 🐠 front-end, ✨ feature, ♻️ refactor

#87 🐟 채팅방 만들기 기능 구현
  client/src/api/index.ts
  client/src/components/chat/chat-header.tsx
  client/src/components/chat/chat-room-layout.tsx
  client/src/components/chat/chat-user-card.tsx
  client/src/components/common/room-card.tsx
  client/src/components/common/user-card-list.tsx
  client/src/recoil/atoms/chat-selected-users.ts
  client/src/routes/main.tsx
  client/src/views/chat-room-detail-view.tsx
  client/src/views/chat-rooms-new-view.tsx
  client/src/views/chat-rooms-view.tsx
  client/src/views/room-view.tsx
  server/src/api/routes/chats.ts
  server/src/api/routes/user.ts
  server/src/models/chats.ts
  server/src/services/chat-service.ts
  server/src/services/users-service.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#88 프로필 페이지 구현
  client/src/components/body-modal.tsx
  client/src/components/common/default-header.tsx
  client/src/components/event/event-header.tsx
  client/src/components/profile/profile-header.tsx
  client/src/components/profile/share-modal.tsx
  client/src/recoil/atoms/is-open-modal.ts
  client/src/routes/header.tsx
  client/src/views/profile-view.tsx
  server/src/api/routes/user.ts
  server/src/models/users.ts
  server/src/services/users-service.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#89 ✨ All 타입 검색기능 구현 완료
  client/src/components/search/style.ts
  client/src/views/search-view.tsx
  server/src/api/routes/search.ts
  server/src/services/rooms-service.ts
  server/src/services/users-service.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#93 채팅방 내부 헤더 구현 및 채팅방 클릭 이벤트 구현
  client/src/components/chat/chat-header.tsx
  client/src/components/chat/chat-list-header.tsx
  client/src/components/chat/chat-new-header.tsx
  client/src/components/chat/chat-room-header.tsx
  client/src/components/chat/chat-room-layout.tsx
  client/src/components/chat/chat-user-card.tsx
  client/src/components/chat/style.ts
  client/src/recoil/atoms/chat-selected-users.ts
  client/src/routes/main.tsx
  client/src/views/chat-room-detail-view.tsx
  client/src/views/chat-rooms-new-view.tsx
  client/src/views/chat-rooms-view.tsx
  server/src/api/routes/chats.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#99 프로필 화면에서 팔로우 버튼 활성화, 기타 관련 기능 구현
  client/src/components/common/event-card.tsx
  client/src/components/common/user-card-list.tsx
  client/src/components/common/user-card.tsx
  client/src/components/profile/followers-header.tsx
  client/src/components/profile/following-header.tsx
  client/src/components/profile/profile-header.tsx
  client/src/hooks/useIsFollowingRef.tsx
  client/src/routes/header.tsx
  client/src/views/followers-view.tsx
  client/src/views/following-view.tsx
  client/src/views/main-view.tsx
  client/src/views/profile-view.tsx
  client/src/views/search-view.tsx
  server/src/api/routes/user.ts
  server/src/services/users-service.ts
Labels: 🐛 bug, ✨ feature

#100 🐛 refreshToken으로 accessToken이 갱신되지 않는 오류 해결
  server/src/api/middlewares/auth.ts
  server/src/models/refresh-token.ts
  server/src/services/users-service.ts
  server/src/utils/jwt-util.ts
Labels: 🐛 bug

#106 💄 모바일 대응 반응형 스타일 구현
  client/src/assets/styles/global-styles.ts
  client/src/assets/styles/keyframe.ts
  client/src/components/common/custom-inputbar.tsx
  client/src/components/common/default-header.tsx
  client/src/components/common/header.tsx
  client/src/components/common/interest-item.tsx
  client/src/components/common/menu-modal.tsx
  client/src/components/room/right-sidebar.tsx
  client/src/components/sign/sign-title.tsx
  client/src/recoil/atoms/is-open-room.ts
  client/src/recoil/atoms/is-open-slider-menu.ts
  client/src/views/main-view.tsx
  client/src/views/signup-info-view.tsx
Labels: 🐠 front-end, ♻️ refactor

#108 채팅방 내부 및 채팅방 목록 추가 구현
  client/src/api/index.ts
  client/src/components/chat/chat-room-footer.tsx
  client/src/components/chat/chat-room-header.tsx
  client/src/components/chat/chat-user-card.tsx
  client/src/components/chat/style.ts
  client/src/components/common/room-card.tsx
  client/src/utils/index.tsx
  client/src/views/chat-room-detail-view.tsx
  client/src/views/chat-rooms-view.tsx
  server/src/api/routes/chats.ts
  server/src/models/chats.ts
  server/src/services/chat-service.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#107 음성 변조 기능 및 이전 PR 통합본
  client/src/api/index.ts
  client/src/assets/images/not-found.gif
  client/src/components/chat/chat-user-card.tsx
  client/src/components/room/in-room-modal.tsx
  client/src/components/room/in-room-user-box.tsx
  client/src/components/room/not-found-room-modal.tsx
  client/src/components/room/right-sidebar.tsx
  client/src/components/room/room-modal.tsx
  client/src/components/room/room-type-check-box.tsx
  client/src/components/room/select-mode-room-modal.tsx
  client/src/hooks/useRtc.tsx
  client/src/recoil/atoms/anonymous.ts
  client/src/recoil/atoms/room-type.ts
  client/src/recoil/atoms/room-view-type.ts
  client/src/recoil/selectors/view-anonymous.ts
  client/src/tests/select-mode-room-modal.test.tsx
  client/src/utils/voice.js
  client/src/utils/voice.ts
  client/src/views/chat-rooms-new-view.tsx
  client/src/views/followers-view.tsx
  client/src/views/main-view.tsx
  client/src/views/room-view.tsx
  client/src/views/search-view.tsx
  server/src/api/routes/user.ts
  server/src/models/rooms.ts
  server/src/services/rooms-service.ts
  server/src/sockets/room.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature, ♻️ refactor

#110 이벤트 관련 view 일부 수정
  client/src/components/common/modal.tsx
  client/src/components/event/event-header.tsx
  client/src/components/event/event-register-modal.tsx
  client/src/views/event-view.tsx
Labels: 🐠 front-end

#111 LeftSIdebar 팔로우 목록 구현
  client/src/components/common/active-following-card.tsx
  client/src/components/event/event-modal.tsx
  client/src/components/left-sidebar.tsx
  client/src/hooks/useRtc.tsx
  client/src/hooks/useSocket.tsx
  client/src/views/main-view.tsx
  client/src/views/profile-view.tsx
  server/src/sockets/index.ts
  server/src/sockets/room.ts
  server/src/sockets/user.ts
Labels: ✨ feature

#112 채팅 기능 구현 마무리
  client/src/components/chat/chat-room-footer.tsx
  client/src/components/chat/chat-user-card.tsx
  client/src/hooks/useSocket.tsx
  client/src/utils/chat-socket.ts
  client/src/views/chat-room-detail-view.tsx
  client/src/views/chat-rooms-view.tsx
  client/src/views/main-view.tsx
  server/src/sockets/chat.ts
  server/src/sockets/index.ts
Labels: 🐠 front-end, 🐟 back-end, 🐛 bug, ✨ feature

#113 익명 음성 채팅 디테일 UI 구현 & 룸 UI 개편 & 인원 초대 UI 구현
  client/src/components/body-modal.tsx
  client/src/components/common/default-button.tsx
  client/src/components/common/modal.tsx
  client/src/components/common/room-card.tsx
  client/src/components/room/follower-select-room-header.tsx
  client/src/components/room/follower-select-room-modal.tsx
  client/src/components/room/in-room-user-box.tsx
  client/src/components/room/right-sidebar.tsx
  client/src/components/room/room-type-check-box.tsx
  client/src/components/room/select-mode-room-modal.tsx
  client/src/components/room/style.ts
  client/src/interfaces/index.ts
  client/src/recoil/atoms/is-open-modal.ts
  client/src/recoil/selectors/view-anonymous.ts
  client/src/views/room-in-view.tsx
  client/src/views/room-new-view.tsx
  client/src/views/room-not-found-view.tsx
  client/src/views/room-select-view.tsx
  client/src/views/room-view.tsx
  server/src/services/rooms-service.ts
  server/src/sockets/room.ts
Labels: 🐠 front-end, 🐛 bug, ✨ feature, ♻️ refactor

#118 채팅방 초대 기능 구현
  client/src/api/index.ts
  client/src/components/chat/chat-list-header.tsx
  client/src/components/chat/chat-new-header.tsx
  client/src/components/chat/chat-room-footer.tsx
  client/src/components/chat/chat-room-header.tsx
  client/src/components/chat/chat-user-card.tsx
  client/src/components/chat/reducer.ts
  client/src/components/chat/style.ts
  client/src/components/room/follower-select-room-modal.tsx
  client/src/views/chat-room-detail-view.tsx
  client/src/views/chat-rooms-view.tsx
  client/src/views/room-in-view.tsx
  server/src/api/routes/chats.ts
  server/src/models/chats.ts
  server/src/services/chat-service.ts
  server/src/sockets/chat.ts
  server/src/sockets/index.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#119 ✨ 프로필 이미지 변경 기능 구현
  client/src/components/left-sidebar.tsx
  client/src/components/profile/change-profile-image-modal.tsx
  client/src/views/profile-view.tsx
  server/package.json
  server/src/api/middlewares/image-upload.ts
  server/src/api/routes/user.ts
  server/src/services/users-service.ts
  server/src/utils/jwt-util.ts
  server/yarn.lock
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#122 select room modal UI 업데이트, 랜덤 매칭 기능 추가
  client/src/api/index.ts
  client/src/assets/styles/scrollbar-style.ts
  client/src/components/common/small-checkbox.tsx
  client/src/components/room/anonymous-checkbox.tsx
  client/src/components/room/follower-select-room-header.tsx
  client/src/components/room/follower-select-room-modal.tsx
  client/src/components/room/in-room-user-box.tsx
  client/src/interfaces/index.ts
  client/src/recoil/atoms/chat-selected-users.ts
  client/src/utils/voice.ts
  client/src/views/room-new-view.tsx
  server/src/api/routes/room.ts
  server/src/services/rooms-service.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature, ♻️ refactor

#120 이벤트 등록 모달 기능 추가
  client/src/api/index.ts
  client/src/components/activity-header.tsx
  client/src/components/common/header.tsx
  client/src/components/common/user-card-list.tsx
  client/src/components/event/event-header.tsx
  client/src/components/event/event-modal.tsx
  client/src/components/event/event-register-modal.tsx
  client/src/components/event/event-select-uesr-dropdown.tsx
  client/src/components/invite-header.tsx
  client/src/components/profile/followers-header.tsx
  client/src/components/profile/following-header.tsx
  client/src/components/profile/profile-header.tsx
  client/src/components/room/follower-select-room-modal.tsx
  client/src/components/search/recent-search-header.tsx
  client/src/components/search/search-header.tsx
  client/src/views/chat-rooms-new-view.tsx
  server/src/api/routes/event.ts
  server/src/api/routes/user.ts
  server/src/services/events-service.ts
  server/src/services/users-service.ts
Labels: ✨ feature

#124 채팅방 관련 데일리 스크럼 피드백 적용
  client/src/assets/styles/scrollbar-style.ts
  client/src/components/chat/chat-new-header.tsx
  client/src/components/chat/style.ts
  client/src/components/common/user-card-list.tsx
  client/src/recoil/atoms/chat-selected-users.ts
  client/src/views/chat-rooms-new-view.tsx
  client/src/views/chat-rooms-view.tsx
Labels: 🐠 front-end, ❓ question, ♻️ refactor

#125 ✨ 로그아웃 기능 구현 & 반응형 마무리
  client/src/api/index.ts
  client/src/assets/styles/global-styles.ts
  client/src/components/activity-header.tsx
  client/src/components/common/default-header.tsx
  client/src/components/common/header.tsx
  client/src/components/common/menu-modal.tsx
  client/src/components/event/event-header.tsx
  client/src/components/invite-header.tsx
  client/src/components/left-sidebar.tsx
  client/src/components/profile/followers-header.tsx
  client/src/components/profile/following-header.tsx
  client/src/components/profile/profile-header.tsx
  client/src/components/search/recent-search-header.tsx
  client/src/components/search/search-header.tsx
  client/src/components/sign/sign-header.tsx
  client/src/hooks/useOutsideClick.tsx
  client/src/recoil/atoms/is-open-active-following-modal.ts
  client/src/utils/index.tsx
  client/src/views/main-view.tsx
Labels: 🐠 front-end, ✨ feature, ♻️ refactor

#126 Toast popup 구현 및 인터페이스 리팩토링
  client/src/App.tsx
  client/src/assets/styles/keyframe.ts
  client/src/components/activity-header.tsx
  client/src/components/chat/chat-new-header.tsx
  client/src/components/chat/chat-user-card.tsx
  client/src/components/chat/style.ts
  client/src/components/common/custom-inputbar.tsx
  client/src/components/common/default-button.tsx
  client/src/components/common/default-header.tsx
  client/src/components/common/interest-item.tsx
  client/src/components/common/room-card.tsx
  client/src/components/common/select.tsx
  client/src/components/common/small-checkbox.tsx
  client/src/components/common/toast.tsx
  client/src/components/common/user-card.tsx
  client/src/components/common/user-image.tsx
  client/src/components/event/event-header.tsx
  client/src/components/event/event-register-modal.tsx
  client/src/components/invite-header.tsx
  client/src/components/left-sidebar.tsx
  client/src/components/profile/profile-header.tsx
  client/src/components/room/follower-select-room-header.tsx
  client/src/components/room/follower-select-room-modal.tsx
  client/src/components/room/in-room-user-box.tsx
  client/src/components/room/right-sidebar.tsx
  client/src/components/search/recent-search-header.tsx
  client/src/components/search/search-header.tsx
  client/src/components/sign/sign-header.tsx
  client/src/components/sign/sign-title.tsx
  client/src/hooks/useRtc.tsx
  client/src/hooks/useSelectUser.tsx
  client/src/interfaces/index.ts
  client/src/recoil/atoms/toast-list.ts
  client/src/recoil/selectors/toast-list.ts
  client/src/utils/index.tsx
  client/src/views/chat-rooms-new-view.tsx
  client/src/views/chat-rooms-view.tsx
  client/src/views/room-in-view.tsx
  client/src/views/room-select-view.tsx
  client/src/views/signin-view.tsx
  client/src/views/signup-info-view.tsx
  client/src/views/signup-view.tsx
Labels: 🐠 front-end, ✨ feature, ♻️ refactor

#127 Activity 기능 구현
  client/src/api/index.ts
  client/src/components/activity/activity-card.tsx
  client/src/components/chat/chat-room-footer.tsx
  client/src/components/common/default-header.tsx
  client/src/components/left-sidebar.tsx
  client/src/hooks/useFetchItems.tsx
  client/src/recoil/atoms/not-read-msg.tsx
  client/src/utils/user-socket.ts
  client/src/views/activity-view.tsx
  client/src/views/chat-room-detail-view.tsx
  client/src/views/chat-rooms-view.tsx
  client/src/views/main-view.tsx
  client/src/views/profile-view.tsx
  server/src/api/index.ts
  server/src/api/routes/activity.ts
  server/src/api/routes/chats.ts
  server/src/api/routes/event.ts
  server/src/api/routes/room.ts
  server/src/api/routes/user.ts
  server/src/models/chats.ts
  server/src/models/users.ts
  server/src/services/chat-service.ts
  server/src/services/events-service.ts
  server/src/services/users-service.ts
  server/src/sockets/chat.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#132 🐟 [J135] 24일차 오늘의 할 일 구현 🐟
  client/src/components/activity/activity-card.tsx
  client/src/components/chat/chat-list-header.tsx
  client/src/components/chat/chat-room-footer.tsx
  client/src/components/common/default-header.tsx
  client/src/components/common/menu-modal.tsx
  client/src/components/common/room-card.tsx
  client/src/views/chat-not-found-view.tsx
  client/src/views/chat-room-detail-view.tsx
  client/src/views/chat-rooms-view.tsx
Labels: 🐠 front-end, ✨ feature, ♻️ refactor

#133 알림기능 실시간 알림 반영
  client/src/components/common/default-header.tsx
  server/src/services/users-service.ts
  server/src/sockets/index.ts
  server/src/sockets/user.ts
Labels: 🐠 front-end, 🐟 back-end, ✨ feature

#134 초대 페이지 구현
  client/src/views/invite-view.tsx
  server/src/api/routes/user.ts
  server/src/services/users-service.ts
Labels: ✨ feature

#135 커스텀 라우터 생성 및 리팩토링
  client/src/App.tsx
  client/src/components/common/default-header.tsx
  client/src/components/common/room-card.tsx
  client/src/components/common/toast.tsx
  client/src/components/profile/change-profile-image-modal.tsx
  client/src/components/room/follower-select-room-header.tsx
  client/src/components/room/style.ts
  client/src/routes/custom/private-route.tsx
  client/src/routes/custom/public-route.tsx
  client/src/routes/header.tsx
  client/src/routes/index.tsx
  client/src/routes/main.tsx
  client/src/utils/index.tsx
  client/src/views/main-init-view.tsx
  client/src/views/main-view.tsx
  client/src/views/room-new-view.tsx
  client/src/views/signin-view.tsx
Labels: 🐠 front-end, ♻️ refactor

#139 채팅방 버그 이슈 및 프로필 사진 변경 모달 UI 수정
  client/src/components/chat/chat-new-header.tsx
  client/src/components/profile/change-profile-image-modal.tsx
  client/src/recoil/selectors/index.ts
  client/src/tests/index.tsx
  client/src/utils/index.tsx
  client/src/views/chat-rooms-new-view.tsx
  server/src/api/routes/chats.ts
  server/src/services/user/activity-service.ts
  server/src/services/user/auth-service.ts
  server/src/services/user/email-service.ts
  server/src/services/user/follow-service.ts
  server/src/services/user/user-service.ts
  server/src/services/users-service.ts
Labels: 🐠 front-end, 🐛 bug, ❓ question, ♻️ refactor

#140 ♻️ 검색 요청 방식 개선(Debouncing)
  client/src/utils/item.ts
  client/src/views/followers-view.tsx
  client/src/views/following-view.tsx
  client/src/views/search-view.tsx
Labels: ♻️ refactor

#141 ♻️ client api 폴더 리팩토링
  client/src/api/user/index.ts
  client/src/api/util.ts
  client/src/views/profile-view.tsx
Labels: ♻️ refactor

#142 ♻️ UI/UX 관련 리팩토링
  client/src/components/common/active-following-card.tsx
  client/src/components/common/custom-inputbar.tsx
  client/src/components/sign/sign-title.tsx
  client/src/hooks/useOutsideClick.tsx
  client/src/routes/header.tsx
  client/src/views/invite-view.tsx
  client/src/views/main-view.tsx
  client/src/views/signup-info-view.tsx
  client/src/views/signup-view.tsx
Labels: 🐠 front-end, ♻️ refactor

#147 음성변조 기능 ver2 & 버그 수정
  client/src/components/body-modal.tsx
  client/src/components/common/small-checkbox.tsx
  client/src/components/room/anonymous-checkbox.test.tsx
  client/src/components/room/anonymous-checkbox.tsx
  client/src/components/room/in-room-user-box.tsx
  client/src/components/room/modal/follower-select-header.tsx
  client/src/components/room/modal/follower-select.tsx
  client/src/components/room/room-type-check-box.tsx
  client/src/components/room/style.ts
  client/src/hooks/useRtc.tsx
  client/src/setupTests.ts
  client/src/utils/jungle.js
  client/src/utils/voice.ts
  client/src/views/room-in-view.tsx
  client/src/views/room-new-view.tsx
  client/src/views/room-select-view.tsx
  client/src/views/room-view.tsx
Labels: 🐠 front-end, 🐛 bug, ✨ feature, ♻️ refactor

#148 채팅방 무한 스크롤 구현
  client/src/api/index.ts
  client/src/components/chat/chat-room-footer.tsx
  client/src/components/chat/reducer.ts
  client/src/components/chat/style.ts
  client/src/components/room/modal/follower-select-header.tsx
  client/src/views/chat-room-detail-view.tsx
  server/src/api/routes/chats.ts
  server/src/services/chat-service.ts
  server/src/sockets/chat.ts
Labels: 🐠 front-end, 🐟 back-end, ♻️ refactor

#150 마이크 없이 입장 이슈 해결 & 일부 코드 리팩토링
  client/src/components/common/toast/style.ts
  client/src/components/room/new-view/index.tsx
  client/src/hooks/useRtc.tsx
Labels: 🐠 front-end, 🐛 bug, ♻️ refactor

#151 유효하지 않은 방 클릭시 모바일 뷰에서 모달창 안나오는 부분 에러 수정
  client/src/components/activity/card/index.tsx
  client/src/components/chat/detail-view/index.tsx
  client/src/components/room/in-view/index.tsx
  client/src/components/room/not-found-view/index.tsx
Labels: 🐠 front-end, 🐛 bug
